version: '3.2'
services:

  smart-launcher: # SMART Launcher ---------------------------------------------
    image: smartonfhir/smart-launcher
    environment:
      NODE_ENV               : "production"
      LAUNCHER_BASE_URL      : "http://${HOST}:${LAUNCHER_PORT}"
      BASE_URL               : "http://${HOST}:${LAUNCHER_PORT}"
      FHIR_SERVER_R2         : "http://${HOST}:${HAPI_PORT_STU2}/baseDstu2"
      FHIR_SERVER_R3         : "http://${HOST}:${HAPI_PORT_STU3}/baseDstu3"
      FHIR_SERVER_R2_INTERNAL: "http://stu2:${HAPI_PORT_STU2}/baseDstu2"
      FHIR_SERVER_R3_INTERNAL: "http://stu3:${HAPI_PORT_STU3}/baseDstu3"
      DISABLE_SANDBOXES      : "1"
      CDS_SANDBOX_URL        : "https://sandbox.cds-hooks.org"
      PICKER_CONFIG_R2       : "dstu2-local"
      PICKER_CONFIG_R3       : "stu3-local"
      PICKER_ORIGIN          : "http://${HOST}:${PATIENT_BROWSER_PORT}"
      STU2_ENABLED           : "${STU2_ENABLED}"
      STU3_ENABLED           : "${STU3_ENABLED}"
    ports:
      - "${LAUNCHER_PORT}:80"
    depends_on:
      - patient-browser
      - fhir-viewer
      - stu3
      - stu2

  stu3: # HAPI STU3 ------------------------------------------------------------
    image: smartonfhir/hapi:r3-empty
    environment:
      PORT        : $HAPI_PORT_STU3
      STU3_ENABLED: $STU3_ENABLED
    ports:
      - "${HAPI_PORT_STU3}:${HAPI_PORT_STU3}"
    volumes:
      - "./${STU3_DATA_DIR}:/data:delegated"
    command: bash -c "if ('$STU3_ENABLED' == 'true'); then bash /app/cmd; fi"

  stu2: # HAPI STU2 ------------------------------------------------------------
    image: smartonfhir/hapi:r2-empty
    environment:
      PORT        : $HAPI_PORT_STU2
      STU2_ENABLED: $STU2_ENABLED
    ports:
      - "${HAPI_PORT_STU2}:${HAPI_PORT_STU2}"
    volumes:
      - "./${STU2_DATA_DIR}:/data:delegated"
    command: bash -c "if ('$STU2_ENABLED' == 'true'); then bash /app/cmd; fi"

  patient-browser: # Patient Browser -------------------------------------------
    image: smartonfhir/patient-browser:node
    ports:
      - "${PATIENT_BROWSER_PORT}:80"
    volumes:
      - ./patient-browser:/usr/share/nginx/html/config
    environment:
      LAUNCHER_PORT   : "${LAUNCHER_PORT}"
      FHIR_VIEWER_PORT: "${FHIR_VIEWER_PORT}"
      HAPI_PORT_STU3  : "${HAPI_PORT_STU3}"
      HAPI_PORT_STU2  : "${HAPI_PORT_STU2}"
      HOST            : "${HOST}"
    command: sh -c "envsubst < /usr/share/nginx/html/config/dstu2-local.tpl > /usr/share/nginx/html/config/dstu2-local.json5 && envsubst < /usr/share/nginx/html/config/stu3-local.tpl > /usr/share/nginx/html/config/stu3-local.json5 && nginx -g 'daemon off;'"

  fhir-viewer: # Fhir Viewer ---------------------------------------------------
    image: smartonfhir/fhir-viewer
    ports:
      - "${FHIR_VIEWER_PORT}:80"
    volumes:
      - ./fhir-viewer:/usr/share/nginx/html/config
    environment:
      HOST: "${HOST}"
    command: sh -c "envsubst < /usr/share/nginx/html/config/known-servers.tpl > /usr/share/nginx/html/known-servers.js && nginx -g 'daemon off;'"

  index: # Index page ----------------------------------------------------------
    image: nginx:alpine
    ports:
      - "${CONTROL_PANEL_PORT}:80"
    volumes:
      - ./www:/usr/share/nginx/html
    environment:
      LAUNCHER_PORT       : "${LAUNCHER_PORT}"
      HAPI_PORT_STU2      : "${HAPI_PORT_STU2}"
      HAPI_PORT_STU3      : "${HAPI_PORT_STU3}"
      PATIENT_BROWSER_PORT: "${PATIENT_BROWSER_PORT}"
      FHIR_VIEWER_PORT    : "${FHIR_VIEWER_PORT}"
      STU2_ENABLED        : "${STU2_ENABLED}"
      STU3_ENABLED        : "${STU3_ENABLED}"
      HOST                : "${HOST}"
      ISSUES_URL          : "https://github.com/smart-on-fhir/smart-dev-sandbox/issues"
    command: sh -c "envsubst < /usr/share/nginx/html/template.html > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
